### ISSUE TITLE
Warp Drive does not appear in stock Tech Tree

### ISSUE THREAD

**Issue by MrKiel** [UmbraSpaceIndustries/WarpDrive#8]
The part.cfg files show that the tech required to unlock is experimental rocketry, which is no longer in the stock tech tree. This may have to be amended for those not using CTT.

**Comment by Blu3wolf** [comment]
Is this intentional? Will CTT become a dependency for the warp drive?

**Comment by helaeon** [comment]
The node that the warp drive used to be unlocked under doesn't exist any more.
For my own game for now I'm using experimentalScience for stock.
In the cfgs you can do "TechRequired = experimentalScience"

Also note the CTT cfg is not correct for CTT 2.0 as TechManager is no longer used so that should also be updated.
